sonar.projectKey=banquito-web-empresas
sonar.projectName=BanQuito Web Empresas Frontend
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.token=sqa_cd54d5f41b0905325b8d3c96bdb14cd73e9d0c9d
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.*,**/*.spec.*
